### ISSUE TITLE
Had a crash adding multiple torrent files

### ISSUE THREAD

**Issue by keithah** [someperson/transgui#1]
1. MacOS 10.14.5
2. 2.94
3. 5.17.0-cocoa-alpha5

Here's the crash log: https://gist.github.com/keithah/40a190c676f767d224682b8aaf135bd1

I added 20 torrent files via the Add Torrent button (highlight all in dialog, then click open) and was modifying path for each one. After the 3 one, it crashed.

I just did the same thing and it did not.

I've also noticed it gets 'lost' in cmd-tab, where I flip between Terminal and sometimes it wont bring the window to focus, I need to right click on the dock icon and goto 'show all windows' for it to appear, and dark mode does not appear enabled:

![image](https://user-images.githubusercontent.com/684920/63720562-2c8a1680-c7eb-11e9-9209-4c17d98901ec.png)
(I have it enabled system wide)

Overall, great build so far! It seems super functional.

(Sorry to mention other issues, if you want me to open up individual issues for them, I can do that)

**Comment by someperson** [comment]
@keithah Would you mind retesting with the build I just published? It was built using an updated toolchain that brought in many fixes and improvements.

**Comment by keithah** [comment]
Looking great! 
I have not had a crash yet, dark mode is successful and cmd-tab works well.

I'll open up an issue if I see any other problems.
